### ISSUE TITLE
[BUG]-Drag issue in Kanban Board

### ISSUE THREAD

**Issue by ApurvaMishra4038** [nirajmohanrana/hashtag-ask#12]
**Describe the bug**
There is an issue kanban board where once once a column is empty the user cant drag the card again

**To Reproduce**
1. Navigate to Home page's Board Section
2. Empty any one column
3. Try to drag a card from any column to that empty column
4. The User is unable to do this

**Expected behavior**
User should able to drag cards on any column without any hassle

**Screenshots**
![image](https://github.com/nirajmohanrana/hashtag-ask/assets/90599408/1157b2e7-e9c6-44e8-9dd2-e10dc58a0e64)

**Reproducible on all devices**

**Comment by nirajmohanrana** [comment]
fixed on commit [aa3134a](https://github.com/nirajmohanrana/hashtag-ask/commit/aa3134a30a441d05c12ba1c4d328e78c563923df)
