### ISSUE TITLE
Animate the Kanban Card on hover effect

### ISSUE THREAD

**Issue by Ankitpal-123** [nirajmohanrana/hashtag-ask#14]
**Is your feature request related to a problem? Please describe.**
When I was useing this and i am not happy with the efffects and the animation of the kanban card

**Describe the solution you'd like**
It solution will be the anomation and the slow down the in and outt hover effect in the card effect

**Describe alternatives you've considered**
Previously I have seen some where the hover effect  like this would be good and I would be like that, to recommend 

https://github.com/nirajmohanrana/hashtag-ask/assets/79321761/80c689d4-1990-4235-b944-e4eb36c48d25

**Comment by krishi-agrawal** [comment]
I would like to work on this issue, can you assign it to me?

**Comment by nirajmohanrana** [comment]
> I would like to work on this issue, can you assign it to me?

Yes i haved assigned to you
The first and best written code would be considered to Merge

Make sure to read [Installation Guide](https://github.com/nirajmohanrana/hashtag-ask/blob/main/README.md#installation) before starting

**Comment by nirajmohanrana** [comment]
Merged PR #15 bt @krishi-agrawal
