### ISSUE TITLE
[BUG] : Board Example Overflowed

### ISSUE THREAD

**Issue by Abhay-Singh-1913** [nirajmohanrana/hashtag-ask#20]
**Describe the bug**
The content exceeds its container's boundaries and overlaps with another element.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Home Page'
2. Scroll down to 'Easy To Manage Boards'
3. Open DevTools
4. Check Responsive
5. See an error

**Expected behavior**
The content must be entirely visible within its designated container without any interference with other elements.

**Screenshots**
![Screenshot 2024-01-04 195213](https://github.com/nirajmohanrana/hashtag-ask/assets/93770368/4934a653-0308-4325-8798-1a078f6031a1)

**Comment by nirajmohanrana** [comment]
https://github.com/nirajmohanrana/hashtag-ask/pull/21
Fixed This

**Comment by nirajmohanrana** [comment]
https://github.com/nirajmohanrana/hashtag-ask/pull/21
Fixed This
