### ISSUE TITLE
Missing HomePage Representation

### ISSUE THREAD

**Issue by SaurabhVishwakarma826** [nirajmohanrana/hashtag-ask#4]
In the current project, there is a notable absence of a dedicated homepage, which serves as the primary landing page for users. A homepage typically provides an overview of the application, introduces key features, and guides users on how to navigate the system. Its absence can lead to a less intuitive user experience and may result in users feeling disoriented when accessing the application.

**Comment by nirajmohanrana** [comment]
Completed this task added a Representation for site
[commit-f5aa102](https://github.com/nirajmohanrana/hashtag-ask/commit/f5aa102234b8becc36b130a6359efe74eb107a64) fixes this
