### ISSUE TITLE
More clearity needed

### ISSUE THREAD

**Issue by SaurabhVishwakarma826** [nirajmohanrana/hashtag-ask#9]
**Describe the bug**
This issue with text overlapping in home page

**Expected behavior**
Adjust the text for clear visual of text in home page

**Screenshots**
![image](https://github.com/nirajmohanrana/hashtag-ask/assets/100016387/05e93ace-080b-4cf8-9727-769c1239c538)

**Comment by nirajmohanrana** [comment]
fixed this on commit [bdacf5d](https://github.com/nirajmohanrana/hashtag-ask/commit/bdacf5d4495818f7e87cbe1f8a1f256c695e4c99)

**Comment by nirajmohanrana** [comment]
Fixed on commit - [bdacf5d](https://github.com/nirajmohanrana/hashtag-ask/commit/bdacf5d4495818f7e87cbe1f8a1f256c695e4c99)
